package org.antipathy.scoozie.builder

/**
  * Object for storing hocon constant names
  */
object HoconConstants {

  val name = "name"
  val arguments = "arguments"
  val javaOptions = "java-options"
  val to = "to"
  val cc = "cc"
  val subject = "subject"
  val body = "body"
  val contentType = "content-type"
  val steps = "steps"
  val jobXml = "job-xml"
  val delete = "delete"
  val mkDir = "mkdir"
  val touchz = "touchz"
  val chmod = "chmod"
  val path = "path"
  val permissions = "permissions"
  val dirFiles = "dir-files"
  val move = "move"
  val source = "source"
  val target = "target"
  val scriptName = "script-name"
  val scriptLocation = "script-location"
  val parameters = "parameters"
  val files = "files"
  val mainClass = "main-class"
  val javaJar = "java-jar"
  val commandLineArguments = "command-line-arguments"
  val captureOutput = "capture-output"
  val script = "script"
  val params = "params"
  val environmentVariables = "environment-variables"
  val sparkMasterUrl = "spark-master-url"
  val sparkMode = "spark-mode"
  val sparkJobName = "spark-job-name"
  val sparkJar = "spark-jar"
  val sparkOptions = "spark-options"
  val command = "command"
  val host = "host"
  val applicationPath = "application-path"
  val propagateConfiguration = "propagate-configuration"
  val configuration = "configuration"
  val credentials = "credentials"
  val typ = "type"
  val coordinator = "coordinator"
  val frequency = "frequency"
  val start = "start"
  val end = "end"
  val timezone = "timezone"
  val prepare = "prepare"
  val distcp = "distcp"
  val email = "email"
  val filesystem = "filesystem"
  val hive = "hive"
  val java = "java"
  val pig = "pig"
  val shell = "shell"
  val spark = "spark"
  val sqoop = "sqoop"
  val ssh = "ssh"
  val subworflow = "subworflow"
  val kill = "kill"
  val fork = "fork"
  val join = "join"
  val decision = "decision"
  val okTo = "ok-to"
  val errorTo = "error-to"
  val default = "default"
  val message = "message"
  val switches = "switches"
  val paths = "paths"
  val validate = "validate"
  val transitions = "transitions"
  val workflow = "workflow"
  val nameNode = "name-node"
  val jobTracker = "job-tracker"
  val yarnConfig = "yarn-config"
}
